### ISSUE TITLE
intermittent error plotting/computing pc object

### ISSUE THREAD

**Issue by e-marshall** [e-marshall/sentinel1_rtc#11]
get a run time error intermittently when trying to plot PC dataset (eg. in pc_asf_vv.ipynb)
error: 
RuntimeError: Error opening 'https://sentinel1euwestrtc.blob.core.windows.net/sentinel1-grd-rtc/GRD/2021/6/7/IW/DV/S1A_IW_GRDH_1SDV_20210607T121352_20210607T121417_038234_048318_0FB2/measurement/iw-vv.rtc.tiff?st=2022-09-26T00%3A00%3A29Z&se=2022-09-28T00%3A00%3A29Z&sp=rl&sv=2021-06-08&sr=c&skoid=c85c15d6-d1ae-42d4-af60-e2ca0f81359b&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-09-26T23%3A41%3A54Z&ske=2022-10-03T23%3A41%3A54Z&sks=b&skv=2021-06-08&sig=HgJEjttFqgZMRQbt8fkh1usToNb6RaHpKItSA7VMmG8%3D': RasterioIOError("'/vsicurl/https://sentinel1euwestrtc.blob.core.windows.net/sentinel1-grd-rtc/GRD/2021/6/7/IW/DV/S1A_IW_GRDH_1SDV_20210607T121352_20210607T121417_038234_048318_0FB2/measurement/iw-vv.rtc.tiff?st=2022-09-26T00%3A00%3A29Z&se=2022-09-28T00%3A00%3A29Z&sp=rl&sv=2021-06-08&sr=c&skoid=c85c15d6-d1ae-42d4-af60-e2ca0f81359b&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47&skt=2022-09-26T23%3A41%3A54Z&ske=2022-10-03T23%3A41%3A54Z&sks=b&skv=2021-06-08&sig=HgJEjttFqgZMRQbt8fkh1usToNb6RaHpKItSA7VMmG8%3D' does not exist in the file system, and is not recognized as a supported dataset name.")

**Comment by dcherian** [comment]
This seems like an intermittent file access error

**Comment by e-marshall** [comment]
tentatively fixed on https://github.com/e-marshall/sentinel1_rtc/commit/c3b4f881a74559da16cab14417930dde0af22b4d though may need to make some other changes later on. Thanks @scottyhq for your help!

**Comment by scottyhq** [comment]
Just writing it down here for future reference. `planetary_computer.sign(stac_item)` produced signed URLs with an expiration date and because Xarray stores those URLs if you come back at some later date and access a cached dataset you'll end up with a 403 forbidden or not found. 

The expiration UTC time is encoded in the URL so in the above example `se=2022-09-28T00` would mean that URL is only valid up until 9/28 at midnight. 

As of now it seems signed URLs are good for 1 week.

**Comment by dcherian** [comment]
As of https://github.com/pydata/xarray/commit/268753696f5886615adf5edd8024e80e40c9d4ea (so xarray > 2022.10.0) this cache should not be active. This would be a good thing to check on xarray `main`
